# -*- coding: utf-8 -*-
"""EPL - Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cEz7NWkbTosCjo69zoSLL5elBKtgH0x1
"""
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from function_epl import *

st.set_page_config(page_title="EPL Score - Can Your Team Win?", page_icon="⚽")

st.header('Can Your Team Win?')
st.write('English Premier League Version')
st.write('This is for FUN only. I made this because I need a portfolio for my data science job (LOL).')
df = read_data('epl-2017-2025-03-20.csv')

left, right = st.columns(2)
left.page_link("pages/2_Predict_Score.py")
page_1 = left.button("START", use_container_width=True, type='primary')
right.page_link("pages/1_See_The_Data.py")
page_2 = right.button("See the Data", use_container_width=True, type='secondary', on_click="https://eplscore-niwxzmlmj92rcszsco3obt.streamlit.app/See_The_Data")

st.caption("Last Update: 20-03-2025")
