# -*- coding: utf-8 -*-
"""EPL - Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cEz7NWkbTosCjo69zoSLL5elBKtgH0x1
"""
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from function_epl import *

st.set_page_config(page_title="EPL Score - Can Your Team Win?", page_icon="⚽")

st.header('Can Your Team Win?')
st.write('English Premier League Version. This is for FUN only')
df = read_data('epl-2017-2025-03-20.csv')

st.page_link("pages/2_Predict_Score.py", label="START PREDICTION")
st.page_link("pages/1_See_The_Data.py", label="See the Data")

st.caption("Last Update: 20-03-2025")
